import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { C_Header } from "@/components/elements/header/page";
import { FooterPage } from "@/components/elements/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " w-full bg-gradient-to-r from-orange-200 to-orange-100 bg-cover"
        }
      >
        <C_Header />
        {children}
        <FooterPage />
      </body>
    </html>
  );
}
